# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener:  false
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  false
    exception:
        enabled: false
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/, priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
