app:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  prefix: /app

api:
  resource:
    path: ../src/Controller/Api/
    namespace: App\Controller\Api
  type: attribute
  prefix: /api

# redirecting the root
root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /app/project
    permanent: true